baseURL = 'https://tbilisi-bitcoin-club.github.io/web/'
title = 'Tbilisi Bitcoin Club'
languageCode = 'ru-ru'
defaultContentLanguage = 'ru-ru'
defaultContentLanguageInSubdir = false
enableEmoji = true

[module]
  [[module.imports]]
    path = 'github.com/hugo-sid/hugo-blog-awesome'

[Languages.ru-ru]
  languageName = 'Russian'
  contentDir = 'content/ru'
  weight = 1

[params]
  customCSS = ["css/custom.css"]
  mainSections = ["posts"]

[build]
  noJSConfigInAssets = true
